# Generated by Django 5.2.1 on 2025-05-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suscrito_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ultimo_cambio_password',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
